name: arabizi_transliterator
description: "A Dart/Flutter package for transliterating Arabizi (Arabic chat alphabet) to Arabic script."
version: 1.0.0
homepage: https://github.com/issaloubani/arabizi-transliterator
publish_to: 'none' # Set to 'none' if not publishing to pub.dev, or remove for default

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true